第71回岐阜大学祭の報告
prog-g/prog-g.github.io pull request #64
Opened 2019-11-16 15:31 UTC by curegit

- [x] [記事の投稿方法と方針](https://github.com/prog-g/prog-g.github.io/wiki/%E8%A8%98%E4%BA%8B%E3%81%AE%E6%8A%95%E7%A8%BF%E6%96%B9%E6%B3%95%E3%81%A8%E6%96%B9%E9%87%9D) を読んだ
- [x] ローカルで見た目を確認した
- [x] lintで文章をチェックした
- [ ] *default.html* の変更箇所にコメントをいれた

## やったこと
- 岐阜大学祭についての報告記事を書いた

2019-11-17 01:29 UTC, hirokisakabe approved these changes

2019-11-18 11:41 UTC, ahuglajbclajep requested changes

2019-11-18 11:41 UTC, ahuglajbclajep commented on _posts/2019-11-16-第71回岐大祭に出展しました.md
> +11/2, 11/3 の 2 日間 岐阜大学祭に出展しました。
```suggestion
11/2, 11/3 の２日間、岐阜大学祭に出展しました。
```

2019-11-18 14:43 UTC, ahuglajbclajep approved these changes

2019-11-18 14:44 UTC, merged